### ISSUE TITLE
Protect map in if clause

### ISSUE THREAD

**Issue by JensAc** [gardener-community/garden-kube-apiserver#1]
This [line](https://github.com/gardener-community/garden-kube-apiserver/blob/da569198d9bc03141fa72134b043789339e9e17a/charts/garden-kube-apiserver/templates/secret-identity-ca.yaml#L15) leads to a failure if `.Values.tls.identity.ca` is not set. 
Therefore, it should be

``` yaml
{{- if ((((.Values).tls).identity).ca) }}
apiVersion: v1
kind: Secret
metadata:
  name: identity-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.identity.ca | b64enc }}
{{- end }}
```
